# coding: utf-8
import os
java_files = []
for root, _, files in os.walk('src/main/java'):
    for file in files:
        if file.endswith('.java'):
            java_files.append(os.path.join(root, file))

reps = {
    "Giá»\ufffd": "Giỏ",
    "Sáº£n": "Sản",
    "nÃ y": "này",
    "đá»§": "đủ",
    "quyá»\ufffdn": "quyền",
    "Ä\ufffdá»‹a": "Địa",
    "Báº¡n": "Bạn",
    "Ä\ufffdáº·t": "Đặt",
    "Ä\ufffd": "Đ",
    "Æ°á»\ufffdi": "ười",
    "á»\ufffd": "ỏ",
    "áº¡": "ạ",
    "á»‹": "ị",
    "Ã ": "í ",
    "Ã\n": "í\n",
    "á» ": "ủ ",
    "giá»\ufffd": "giỏ",
    "Ä‘Æ°á»£c": "được",
    "Ä‘": "đ",
    "ngÆ°á»\ufffdi": "người",
    "khÃ´ng": "không",
    "tÃ¬m": "tìm",
    "tháº¥y": "thấy",
    "hoáº·c": "hoặc",
    "sá»‘": "số",
    "Ä‘iá»‡n": "điện",
    "thoáº¡i": "thoại",
    "khá»›p": "khớp",
    "thÃ¢n": "thân",
    "thiá»‡n": "thiện",
    "Chuyá»ƒn": "Chuyển",
    "cÃ¡c": "các",
    "kÃ½": "ký",
    "tá»±": "tự",
    "tiáº¿ng": "tiếng",
    "Viá»‡t": "Việt",
    "Ä‘áº·c": "đặc",
    "biá»‡t": "biệt",
    "thá»§": "thủ",
    "cÃ´ng": "công",
    "VÃ¬": "Vì",
    "xá»­": "xử",
    "lÃ½": "lý",
    "triá»‡t": "triệt",
    "chá»¯": "chữ",
    "Chuáº©n": "Chuẩn",
    "hÃ³a": "hóa",
    "chuá»—i": "chuỗi",
    "TÃ¡ch": "Tách",
    "dáº¥u": "dấu",
    "khá»\ufffdi": "khỏi",
    "DÃ¹ng": "Dùng",
    "Ä‘á»ƒ": "để",
    "loáº¡i": "loại",
    "bá»\ufffd": "bỏ",
    "Ä‘Ã£": "đã",
    "tÃ¡ch": "tách",
    "Thay": "Thay",
    "tháº¿": "thế",
    "khoáº£ng": "khoảng",
    "tráº¯ng": "trắng",
    "báº±ng": "bằng",
    "gáº¡ch": "gạch",
    "ngang": "ngang",
    "Loáº¡i": "Loại",
    "khÃ´ng": "không",
    "pháº£i": "phải",
    "sá»‘": "số",
    "Gá»™p": "Gộp",
    "nhiá»\ufffdu": "nhiều",
    "liÃªn": "liên",
    "tiáº¿p": "tiếp",
    "thÃ nh": "thành",
    "vÃ­": "ví",
    "dá»¥": "dụ",
    "Cáº¯t": "Cắt",
    "á»Ÿ": "ở",
    "Ä‘áº§u": "đầu",
    "vÃ ": "và",
    "cuá»‘i": "cuối",
    "náº¿u": "nếu",
    "cÃ³": "có",
    "Táº¡o": "Tạo",
    "chÆ°a": "chưa",
    "LÆ°u": "Lưu",
    "tráº£": "trả",
    "vá»\ufffd": "về",
    "tÃªn": "tên",
    "XÃ³a": "Xóa",
    "HÃ m": "Hàm",
    "chÃ­nh": "chính",
    "vÃ£ng": "vãng",
    "lai": "lai",
    "ThÃ´ng": "Thông",
    "tin": "tin",
    "ngÆ°á»\ufffdi": "người",
    "nháº­n": "nhận",
    "Tá»«": "Từ",
    "gá»­i": "gửi",
    "lÃªn": "lên",
    "Láº¥y": "Lấy",
    "táº¥t": "tất",
    "cáº£": "cả",
    "chi": "chi",
    "tiáº¿t": "tiết",
    "Cáº­p": "Cập",
    "nháº­t": "nhật",
    "tráº¡ng": "trạng",
    "thÃ¡i": "thái",
    "Duyá»‡t": "Duyệt",
    "Há»§y": "Hủy",
    "nghiá»‡p": "nghiệp",
    "vá»¥": "vụ",
    "MÃ£": "Mã",
    "máº­t": "mật",
    "kháº©u": "khẩu",
    "thá»\ufffdi": "thời",
    "gian": "gian",
    "táº¡o": "tạo",
    "máº·c": "mặc",
    "Ä‘á»‹nh": "định",
    "má»›i": "mới",
    "thá»ƒ": "thể",
    "Chá»‰": "Chỉ",
    "cÃ¡c": "các",
    "trÆ°á»\ufffdng": "trường",
    "cho": "cho",
    "phÃ©p": "phép",
    "má»\ufffdm": "mềm",
    "cá»©ng": "cứng",
    "Kiá»ƒm": "Kiểm",
    "tra": "tra",
    "xÃ¡c": "xác",
    "nháº­n": "nhận",
    "Xá»¬": "XỬ",
    "LÃ\ufffd": "LÝ", 
    "GIá»šI": "GIỚI",
    "TÃ\ufffdNH": "TÍNH",
    "hoa": "hoa",
    "Giá»\ufffd": "Giỏ",
    "Sáº£n": "Sản",
    "Ä\ufffdá»‹a": "Địa",
    "quyá»\ufffdn": "quyền",
    "bá»\ufffd": "bỏ",
    "ngÆ°á»\ufffdi": "người",
    "thá»\ufffdi": "thời",
    "khá»\ufffdi": "khỏi",
    "trá»\ufffd": "trở",
    "LÃ\ufffd": "LÝ",
    "TÃ\ufffdNH": "TÍNH",
    "Ä\ufffdáº·t": "Đặt",
    "Ä\ufffdá»‹a": "Địa",
    "Ä\ufffdÆ°á»£c": "Được",
    "Ä\ufffdÃ£": "Đã",
    "Ä\ufffd": "Đ",
    "trá»\ufffdng": "trường",
    "truyá»\ufffdn": "truyền",
    "á»Ÿ": "ở",
    "trá»\ufffd": "trở",
    "ná»\ufffdi": "nổi",
    "Ä‘á»•i": "đổi",
    "lá»—i": "lỗi"
}

sorted_reps = sorted(reps.items(), key=lambda x: len(x[0]), reverse=True)

changed_count = 0
for path in java_files:
    with open(path, 'r', encoding='utf-8') as file:
        content = file.read()
        
    new_content = content
    for bad, good in sorted_reps:
        if bad in new_content:
            new_content = new_content.replace(bad, good)
            
    if new_content != content:
        with open(path, 'w', encoding='utf-8') as file:
            file.write(new_content)
        changed_count += 1

print(f'Fixed {changed_count} files.')
