spring:
  application:
    name: fashionshop

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/FashionDB}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:123456}
    driver-class-name: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: update   # Hoặc validate nếu DB đã có sẵn
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect